name: rocketpool-testnet
services:
  jwtgen:
    image: alpine:3.20
    command: >
      sh -lc '
        mkdir -p /jwt;
        [ -s /jwt/jwtsecret ] || (head -c 32 /dev/urandom | od -An -tx1 | tr -d " \n" > /jwt/jwtsecret);
        echo "JWT ready";
      '
    volumes:
      - ./jwt:/jwt
    restart: "no"

  el-init:
    image: ethereum/client-go:latest
    depends_on: [jwtgen]
    volumes:
      - el-data:/data
      - ./el/genesis.json:/genesis/genesis.json:ro
    command: ["init", "--datadir", "/data", "/genesis/genesis.json"]
    restart: "no"

  el:
    image: ethereum/client-go:latest
    container_name: rp-el
    restart: unless-stopped
    depends_on:
      el-init:
        condition: service_completed_successfully
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    volumes:
      - el-data:/data
      - ./jwt/jwtsecret:/jwt/jwtsecret:ro
    command:
      [
        "--datadir","/data",
        "--networkid","3151908",
        "--port","30303",
        "--discovery.port","30303",
        "--bootnodes","enode://edf16ef10348444679aa8c22cc665f2a44640fb062bc8e051fae8f0cb490fb83ac3bb41ee02c7af1bd7d4bbb05ac5f050249302553516e5d7f125844410b9ed0@57.128.20.31:32000",
        "--nat","extip:${PUBLIC_IP:-0.0.0.0}",
        "--http","--http.addr","0.0.0.0","--http.port","8545",
        "--http.api","eth,net,web3,engine,admin,txpool",
        "--http.corsdomain","*","--http.vhosts","*",
        "--ws","--ws.addr","0.0.0.0","--ws.port","8546","--ws.api","eth,net,web3",
        "--authrpc.addr","0.0.0.0","--authrpc.port","8551","--authrpc.vhosts","*",
        "--authrpc.jwtsecret","/jwt/jwtsecret"
      ]

  cl:
    image: sigp/lighthouse:latest
    container_name: rp-cl
    restart: unless-stopped
    depends_on:
      el:
        condition: service_started
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "4000:4000"
    volumes:
      - cl-data:/data
      - ./cl/config.yaml:/genesis/config.yaml:ro
      - ./cl/genesis.ssz:/genesis/genesis.ssz:ro
      - ./cl/deposit_contract_block.txt:/genesis/deposit_contract_block.txt:ro   # <- REQUIRED
      - ./jwt/jwtsecret:/jwt/jwtsecret:ro
    entrypoint: ["lighthouse"]
    command:
      [
        "beacon_node",
        "--datadir","/data",
        "--boot-nodes","enr:-OK4QDwaZ_OyUmkcc6yo_FK101V8ijG6oDUlXf1GMyPXIfIIXxiEHFSYAX1984RJ0uRpqnRFtky2huM5g9KrsQDGjKoHh2F0dG5ldHOIAAAYAAAAAACGY2xpZW501opMaWdodGhvdXNlijguMC4wLXJjLjCEZXRoMpDk6yg0YAAAOP__________gmlkgnY0gmlwhDmAFB-EcXVpY4KA64lzZWNwMjU2azGhAkoE2cCx5k2fBwUo4Ni7iJ5Q6zARbu2DCOf-Es72CiaIiHN5bmNuZXRzD4N0Y3CCgOiDdWRwgoDo",
        "--enr-address","${PUBLIC_IP:-0.0.0.0}",
        "--enr-tcp-port","9000",
        "--enr-udp-port","9000",
        "--http","--http-address","0.0.0.0","--http-port","4000",
        "--testnet-dir","/genesis",
        "--execution-endpoint","http://el:8551",
        "--execution-jwt","/jwt/jwtsecret"
      ]

  vc:
    image: sigp/lighthouse:latest
    container_name: rp-vc
    restart: unless-stopped
    depends_on:
      cl:
        condition: service_started
    environment:
      - FEE_RECIPIENT=${FEE_RECIPIENT:-0x0000000000000000000000000000000000000000}
    ports:
      - "5062:5062"
    volumes:
      - vc-data:/data
      - ./cl/config.yaml:/genesis/config.yaml:ro
      - ./cl/genesis.ssz:/genesis/genesis.ssz:ro
      - ./cl/deposit_contract_block.txt:/genesis/deposit_contract_block.txt:ro
      - ./validators/keys:/data/validators
      - ./validators/secrets:/data/secrets
    entrypoint: [ "lighthouse" ]
    command:
      [
        "validator_client",
        "--datadir","/data",
        "--testnet-dir","/genesis",
        "--beacon-nodes","http://cl:4000",
        "--suggested-fee-recipient","${FEE_RECIPIENT}",
        "--init-slashing-protection",
        "--http","--http-address","0.0.0.0","--http-port","5062",
        "--unencrypted-http-transport"
      ]

volumes:
  el-data:
  cl-data:
  vc-data: